version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "node-redis-task"
        LoadBalancerInfo:
          ContainerName: "app"
          ContainerPort: 8081
